

export const mockEvents = [
    {
        id: "1",
        title: "Festival de Música Eletrônica 2024",
        description:
            "O maior festival de música eletrônica do Brasil está de volta! Prepare-se para uma noite inesquecível com os melhores DJs nacionais e internacionais. Uma experiência única com efeitos visuais impressionantes e som de alta qualidade.",
        startDate: "2024-07-15T20:00:00Z",
        endDate: "2024-07-16T04:00:00Z",
        locationName: "Espaço das Américas",
        locationAddress: "Rua Tagipuru, 795 - Barra Funda",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Música",
        ageRating: "18+",
        coverImage: "/placeholder.svg?height=400&width=600&text=Festival+Eletrônico",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Festival+Banner",
        status: "active",
        createdAt: "2024-01-15T00:00:00Z",
        updatedAt: "2024-01-15T00:00:00Z",
        userId: "producer1",
    },
    {
        id: "2",
        title: "Stand-up Comedy Night",
        description:
            "Uma noite repleta de risadas com os melhores comediantes do país. Venha se divertir e esquecer os problemas do dia a dia! Humor inteligente e muita diversão garantida.",
        startDate: "2024-06-20T21:00:00Z",
        endDate: "2024-06-20T23:30:00Z",
        locationName: "Teatro Bradesco",
        locationAddress: "Rua Palestra Itália, 500 - Perdizes",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Comédia",
        ageRating: "16+",
        coverImage: "/placeholder.svg?height=400&width=600&text=Comedy+Night",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Comedy+Banner",
        status: "active",
        createdAt: "2024-01-10T00:00:00Z",
        updatedAt: "2024-01-10T00:00:00Z",
        userId: "producer2",
    },
    {
        id: "3",
        title: "Conferência de Tecnologia 2024",
        description:
            "O maior evento de tecnologia do ano! Palestras inspiradoras, networking e as últimas tendências em inovação tecnológica. Conecte-se com profissionais da área e descubra o futuro da tech.",
        startDate: "2024-08-10T09:00:00Z",
        endDate: "2024-08-10T18:00:00Z",
        locationName: "Centro de Convenções Frei Caneca",
        locationAddress: "Rua Frei Caneca, 569 - Consolação",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Tecnologia",
        ageRating: "Livre",
        coverImage: "/placeholder.svg?height=400&width=600&text=Tech+Conference",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Tech+Banner",
        status: "active",
        createdAt: "2024-01-05T00:00:00Z",
        updatedAt: "2024-01-05T00:00:00Z",
        userId: "producer3",
    },
    {
        id: "4",
        title: "Festival Gastronômico - Sabores do Brasil",
        description:
            "Descubra sabores únicos com os melhores chefs da cidade. Uma experiência culinária inesquecível para toda a família. Pratos tradicionais e inovações gastronômicas em um só lugar.",
        startDate: "2024-09-05T12:00:00Z",
        endDate: "2024-09-05T22:00:00Z",
        locationName: "Parque Ibirapuera",
        locationAddress: "Av. Paulista, 1578 - Bela Vista",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Gastronomia",
        ageRating: "Livre",
        coverImage: "/placeholder.svg?height=400&width=600&text=Festival+Gastronômico",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Gastronomia+Banner",
        status: "active",
        createdAt: "2024-01-20T00:00:00Z",
        updatedAt: "2024-01-20T00:00:00Z",
        userId: "producer4",
    },
    {
        id: "5",
        title: "Peça Teatral: Romeu e Julieta",
        description:
            "A clássica história de amor de Shakespeare ganha vida no palco com uma montagem moderna e emocionante. Uma produção que emociona e encanta plateias de todas as idades.",
        startDate: "2024-07-30T19:30:00Z",
        endDate: "2024-07-30T22:00:00Z",
        locationName: "Teatro Municipal",
        locationAddress: "Praça Ramos de Azevedo, s/n - República",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Teatro",
        ageRating: "12+",
        coverImage: "/placeholder.svg?height=400&width=600&text=Romeu+e+Julieta",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Teatro+Banner",
        status: "active",
        createdAt: "2024-01-12T00:00:00Z",
        updatedAt: "2024-01-12T00:00:00Z",
        userId: "producer5",
    },
    {
        id: "6",
        title: "Rock Festival 2024",
        description:
            "O maior festival de rock do país com bandas nacionais e internacionais. Uma noite épica para os amantes do rock com muito som e energia.",
        startDate: "2024-08-25T19:00:00Z",
        endDate: "2024-08-26T02:00:00Z",
        locationName: "Allianz Parque",
        locationAddress: "Rua Palestra Itália, 200 - Perdizes",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Música",
        ageRating: "16+",
        coverImage: "/placeholder.svg?height=400&width=600&text=Rock+Festival",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Rock+Banner",
        status: "active",
        createdAt: "2024-01-25T00:00:00Z",
        updatedAt: "2024-01-25T00:00:00Z",
        userId: "producer6",
    },
    {
        id: "7",
        title: "Workshop de Fotografia",
        description:
            "Aprenda técnicas avançadas de fotografia com profissionais renomados. Workshop prático com equipamentos profissionais e dicas exclusivas.",
        startDate: "2024-06-15T14:00:00Z",
        endDate: "2024-06-15T18:00:00Z",
        locationName: "Estúdio Luz & Sombra",
        locationAddress: "Rua Augusta, 1000 - Consolação",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Educação",
        ageRating: "Livre",
        coverImage: "/placeholder.svg?height=400&width=600&text=Workshop+Fotografia",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Fotografia+Banner",
        status: "active",
        createdAt: "2024-01-08T00:00:00Z",
        updatedAt: "2024-01-08T00:00:00Z",
        userId: "producer7",
    },
    {
        id: "8",
        title: "Feira de Arte e Artesanato",
        description:
            "Exposição e venda de obras de arte e artesanato local. Apoie artistas independentes e encontre peças únicas e exclusivas.",
        startDate: "2024-07-20T10:00:00Z",
        endDate: "2024-07-20T18:00:00Z",
        locationName: "Praça da República",
        locationAddress: "Praça da República, s/n - República",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Arte",
        ageRating: "Livre",
        coverImage: "/placeholder.svg?height=400&width=600&text=Feira+de+Arte",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Arte+Banner",
        status: "active",
        createdAt: "2024-01-18T00:00:00Z",
        updatedAt: "2024-01-18T00:00:00Z",
        userId: "producer8",
    },
    {
        id: "9",
        title: "Corrida Noturna 10K",
        description:
            "Corrida noturna de 10 quilômetros pelas principais avenidas da cidade. Evento esportivo com premiação e kit completo para os participantes.",
        startDate: "2024-09-15T19:00:00Z",
        endDate: "2024-09-15T22:00:00Z",
        locationName: "Parque do Ibirapuera",
        locationAddress: "Av. Paulista, 1578 - Bela Vista",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Esportes",
        ageRating: "16+",
        coverImage: "/placeholder.svg?height=400&width=600&text=Corrida+Noturna",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Corrida+Banner",
        status: "active",
        createdAt: "2024-01-22T00:00:00Z",
        updatedAt: "2024-01-22T00:00:00Z",
        userId: "producer9",
    },
    {
        id: "10",
        title: "Festival de Cinema Independente",
        description:
            "Mostra de filmes independentes com diretores emergentes. Sessões especiais, debates e premiação dos melhores filmes do festival.",
        startDate: "2024-10-05T18:00:00Z",
        endDate: "2024-10-05T23:00:00Z",
        locationName: "Cine Belas Artes",
        locationAddress: "Rua da Consolação, 2423 - Consolação",
        locationCity: "São Paulo",
        locationState: "SP",
        category: "Cinema",
        ageRating: "14+",
        coverImage: "/placeholder.svg?height=400&width=600&text=Festival+Cinema",
        bannerImage: "/placeholder.svg?height=300&width=1200&text=Cinema+Banner",
        status: "active",
        createdAt: "2024-01-30T00:00:00Z",
        updatedAt: "2024-01-30T00:00:00Z",
        userId: "producer10",
    },
]

export const mockSectors = [
    // Evento 1 - Festival de Música Eletrônica
    {
        id: "sector1",
        eventId: "1",
        name: "Pista Premium",
        description: "Área VIP próxima ao palco principal",
        capacity: 1000,
        color: "#FF6B6B",
    },
    {
        id: "sector2",
        eventId: "1",
        name: "Pista Geral",
        description: "Área geral do festival",
        capacity: 3000,
        color: "#4ECDC4",
    },
    {
        id: "sector3",
        eventId: "1",
        name: "Camarote",
        description: "Área exclusiva com bar e vista privilegiada",
        capacity: 200,
        color: "#45B7D1",
    },

    // Evento 2 - Stand-up Comedy
    {
        id: "sector4",
        eventId: "2",
        name: "Plateia A",
        description: "Primeiras fileiras",
        capacity: 200,
        color: "#96CEB4",
    },
    {
        id: "sector5",
        eventId: "2",
        name: "Plateia B",
        description: "Fileiras intermediárias",
        capacity: 400,
        color: "#FFEAA7",
    },
    {
        id: "sector6",
        eventId: "2",
        name: "Balcão",
        description: "Área superior do teatro",
        capacity: 200,
        color: "#DDA0DD",
    },

    // Evento 3 - Conferência de Tecnologia
    {
        id: "sector7",
        eventId: "3",
        name: "Auditório Principal",
        description: "Palestras principais",
        capacity: 1500,
        color: "#74B9FF",
    },
    {
        id: "sector8",
        eventId: "3",
        name: "Sala de Workshops",
        description: "Atividades práticas",
        capacity: 500,
        color: "#A29BFE",
    },

    // Evento 4 - Festival Gastronômico
    {
        id: "sector9",
        eventId: "4",
        name: "Área Gourmet",
        description: "Restaurantes premium",
        capacity: 1000,
        color: "#FD79A8",
    },
    {
        id: "sector10",
        eventId: "4",
        name: "Praça de Alimentação",
        description: "Food trucks e barracas",
        capacity: 2000,
        color: "#FDCB6E",
    },

    // Evento 5 - Teatro
    {
        id: "sector11",
        eventId: "5",
        name: "Plateia",
        description: "Assentos da plateia",
        capacity: 800,
        color: "#E17055",
    },
    {
        id: "sector12",
        eventId: "5",
        name: "Balcão Nobre",
        description: "Camarotes superiores",
        capacity: 400,
        color: "#00B894",
    },

    // Eventos adicionais (6-10) - um setor cada para simplicidade
    {
        id: "sector13",
        eventId: "6",
        name: "Pista",
        description: "Área principal do festival",
        capacity: 5000,
        color: "#6C5CE7",
    },
    {
        id: "sector14",
        eventId: "7",
        name: "Sala de Workshop",
        description: "Espaço para atividades práticas",
        capacity: 30,
        color: "#00CEC9",
    },
    {
        id: "sector15",
        eventId: "8",
        name: "Área de Exposição",
        description: "Espaço para stands e exposições",
        capacity: 500,
        color: "#FDCB6E",
    },
    {
        id: "sector16",
        eventId: "9",
        name: "Largada/Chegada",
        description: "Área de concentração dos corredores",
        capacity: 1000,
        color: "#E84393",
    },
    {
        id: "sector17",
        eventId: "10",
        name: "Sala de Cinema",
        description: "Assentos do cinema",
        capacity: 200,
        color: "#2D3436",
    },
]

export const mockBatches = [
    // Evento 1 - Festival de Música Eletrônica
    {
        id: "batch1",
        eventId: "1",
        sectorId: "sector1",
        name: "1º Lote - Pista Premium",
        price: 180.0,
        quantity: 500,
        soldQuantity: 450,
        isActive: true,
        startDate: "2024-02-01T00:00:00Z",
        endDate: "2024-04-30T23:59:59Z",
    },
    {
        id: "batch2",
        eventId: "1",
        sectorId: "sector1",
        name: "2º Lote - Pista Premium",
        price: 220.0,
        quantity: 500,
        soldQuantity: 200,
        isActive: true,
        startDate: "2024-05-01T00:00:00Z",
        endDate: "2024-07-14T23:59:59Z",
    },
    {
        id: "batch3",
        eventId: "1",
        sectorId: "sector2",
        name: "1º Lote - Pista Geral",
        price: 80.0,
        quantity: 1500,
        soldQuantity: 1200,
        isActive: true,
        startDate: "2024-02-01T00:00:00Z",
        endDate: "2024-04-30T23:59:59Z",
    },
    {
        id: "batch4",
        eventId: "1",
        sectorId: "sector2",
        name: "2º Lote - Pista Geral",
        price: 100.0,
        quantity: 1500,
        soldQuantity: 800,
        isActive: true,
        startDate: "2024-05-01T00:00:00Z",
        endDate: "2024-07-14T23:59:59Z",
    },
    {
        id: "batch5",
        eventId: "1",
        sectorId: "sector3",
        name: "Camarote VIP",
        price: 350.0,
        quantity: 200,
        soldQuantity: 150,
        isActive: true,
        startDate: "2024-02-01T00:00:00Z",
        endDate: "2024-07-14T23:59:59Z",
    },

    // Evento 2 - Stand-up Comedy
    {
        id: "batch6",
        eventId: "2",
        sectorId: "sector4",
        name: "Plateia A",
        price: 120.0,
        quantity: 200,
        soldQuantity: 180,
        isActive: true,
        startDate: "2024-03-01T00:00:00Z",
        endDate: "2024-06-19T23:59:59Z",
    },
    {
        id: "batch7",
        eventId: "2",
        sectorId: "sector5",
        name: "Plateia B",
        price: 80.0,
        quantity: 400,
        soldQuantity: 350,
        isActive: true,
        startDate: "2024-03-01T00:00:00Z",
        endDate: "2024-06-19T23:59:59Z",
    },
    {
        id: "batch8",
        eventId: "2",
        sectorId: "sector6",
        name: "Balcão",
        price: 60.0,
        quantity: 200,
        soldQuantity: 120,
        isActive: true,
        startDate: "2024-03-01T00:00:00Z",
        endDate: "2024-06-19T23:59:59Z",
    },

    // Evento 3 - Conferência de Tecnologia
    {
        id: "batch9",
        eventId: "3",
        sectorId: "sector7",
        name: "Ingresso Auditório",
        price: 150.0,
        quantity: 1500,
        soldQuantity: 1000,
        isActive: true,
        startDate: "2024-04-01T00:00:00Z",
        endDate: "2024-08-09T23:59:59Z",
    },
    {
        id: "batch10",
        eventId: "3",
        sectorId: "sector8",
        name: "Workshop Premium",
        price: 250.0,
        quantity: 500,
        soldQuantity: 200,
        isActive: true,
        startDate: "2024-04-01T00:00:00Z",
        endDate: "2024-08-09T23:59:59Z",
    },

    // Evento 4 - Festival Gastronômico
    {
        id: "batch11",
        eventId: "4",
        sectorId: "sector9",
        name: "Área Gourmet",
        price: 90.0,
        quantity: 1000,
        soldQuantity: 600,
        isActive: true,
        startDate: "2024-05-01T00:00:00Z",
        endDate: "2024-09-04T23:59:59Z",
    },
    {
        id: "batch12",
        eventId: "4",
        sectorId: "sector10",
        name: "Praça de Alimentação",
        price: 45.0,
        quantity: 2000,
        soldQuantity: 1200,
        isActive: true,
        startDate: "2024-05-01T00:00:00Z",
        endDate: "2024-09-04T23:59:59Z",
    },

    // Evento 5 - Teatro
    {
        id: "batch13",
        eventId: "5",
        sectorId: "sector11",
        name: "Plateia",
        price: 100.0,
        quantity: 800,
        soldQuantity: 600,
        isActive: true,
        startDate: "2024-04-15T00:00:00Z",
        endDate: "2024-07-29T23:59:59Z",
    },
    {
        id: "batch14",
        eventId: "5",
        sectorId: "sector12",
        name: "Balcão Nobre",
        price: 150.0,
        quantity: 400,
        soldQuantity: 300,
        isActive: true,
        startDate: "2024-04-15T00:00:00Z",
        endDate: "2024-07-29T23:59:59Z",
    },

    // Eventos adicionais (6-10)
    {
        id: "batch15",
        eventId: "6",
        sectorId: "sector13",
        name: "Pista Rock",
        price: 120.0,
        quantity: 5000,
        soldQuantity: 3500,
        isActive: true,
        startDate: "2024-05-01T00:00:00Z",
        endDate: "2024-08-24T23:59:59Z",
    },
    {
        id: "batch16",
        eventId: "7",
        sectorId: "sector14",
        name: "Workshop Fotografia",
        price: 200.0,
        quantity: 30,
        soldQuantity: 25,
        isActive: true,
        startDate: "2024-04-01T00:00:00Z",
        endDate: "2024-06-14T23:59:59Z",
    },
    {
        id: "batch17",
        eventId: "8",
        sectorId: "sector15",
        name: "Entrada Feira",
        price: 15.0,
        quantity: 500,
        soldQuantity: 200,
        isActive: true,
        startDate: "2024-06-01T00:00:00Z",
        endDate: "2024-07-19T23:59:59Z",
    },
    {
        id: "batch18",
        eventId: "9",
        sectorId: "sector16",
        name: "Inscrição Corrida",
        price: 80.0,
        quantity: 1000,
        soldQuantity: 750,
        isActive: true,
        startDate: "2024-07-01T00:00:00Z",
        endDate: "2024-09-14T23:59:59Z",
    },
    {
        id: "batch19",
        eventId: "10",
        sectorId: "sector17",
        name: "Ingresso Festival",
        price: 25.0,
        quantity: 200,
        soldQuantity: 120,
        isActive: true,
        startDate: "2024-08-01T00:00:00Z",
        endDate: "2024-10-04T23:59:59Z",
    },
]

export const mockCategories = [
    "Música",
    "Comédia",
    "Tecnologia",
    "Gastronomia",
    "Teatro",
    "Educação",
    "Arte",
    "Esportes",
    "Cinema",
]
